"""Adding nd_id to interaction data schema

Revision ID: 041998d0e01b
Revises: d8095738c7b1
Create Date: 2024-01-24 14:36:51.875374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041998d0e01b'
down_revision = 'd8095738c7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DashboardEvent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notebook_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DashboardEvent', schema=None) as batch_op:
        batch_op.drop_column('notebook_id')

    # ### end Alembic commands ###
