"""add composite index on Event(notebook_id, user_id)

Revision ID: 0b56e41f01e8
Revises: c54c88b8d734
Create Date: 2026-03-18 16:23:01.160634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b56e41f01e8'
down_revision = 'c54c88b8d734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.create_index('idx_event_notebook_user', ['notebook_id', 'user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.drop_index('idx_event_notebook_user')

    # ### end Alembic commands ###
