"""Remove redundant polymorphism

Revision ID: 25baa146fc70
Revises: 8c7f88622305
Create Date: 2023-12-05 15:29:41.915411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25baa146fc70'
down_revision = '8c7f88622305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ClickEvent', schema=None) as batch_op:
        batch_op.drop_column('click_origin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ClickEvent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('click_origin', sa.VARCHAR(length=32), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
