"""Adding user id type column in whitelist table

Revision ID: 29d8b340e958
Revises: 01d8648b5f3b
Create Date: 2024-01-29 16:02:51.393107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d8b340e958'
down_revision = '01d8648b5f3b'
branch_labels = None
depends_on = None

UserIdType = sa.Enum('UUID', 'SCIPER', name='UserIdType')

def upgrade():

    UserIdType.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserWhiteList', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id_type', UserIdType, nullable=False, server_default='UUID'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserWhiteList', schema=None) as batch_op:
        batch_op.drop_column('user_id_type')

    UserIdType.drop(op.get_bind())

    # ### end Alembic commands ###
