"""Adding index to Notebook.notebook_id

Revision ID: 4098e65c5659
Revises: 
Create Date: 2023-11-02 16:44:33.077744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4098e65c5659'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notebook', schema=None) as batch_op:
        batch_op.drop_constraint('Notebook_notebook_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_Notebook_notebook_id'), ['notebook_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notebook', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Notebook_notebook_id'))
        batch_op.create_unique_constraint('Notebook_notebook_id_key', ['notebook_id'])

    # ### end Alembic commands ###
