"""Adding UserGroups & Users & association tables

Revision ID: 6244d32eb37c
Revises: e2bb40880040
Create Date: 2024-03-18 14:10:34.365830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6244d32eb37c'
down_revision = 'e2bb40880040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserGroups',
    sa.Column('group_pk', sa.String(length=401), nullable=False),
    sa.Column('group_name', sa.String(length=300), nullable=False),
    sa.Column('notebook_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('group_pk')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('UserGroupAssociation',
    sa.Column('group_pk', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['group_pk'], ['UserGroups.group_pk'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserGroupAssociation')
    op.drop_table('Users')
    op.drop_table('UserGroups')
    # ### end Alembic commands ###
