"""Update DashboardEvent enum and nullability

Revision ID: 8c7f88622305
Revises: 4098e65c5659
Create Date: 2023-12-01 10:25:19.993927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c7f88622305'
down_revision = '4098e65c5659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DashboardEvent', schema=None) as batch_op:
        batch_op.alter_column('dashboard_user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('click_type',
               existing_type=postgresql.ENUM('ON', 'OFF', name='clicktype'),
               nullable=False)
        batch_op.alter_column('signal_origin',
               existing_type=postgresql.ENUM('DASHBOARD_ICON_LEFT', 'DASHBOARD_ICON_RIGHT', 'NOTEBOOK_CELL_BUTTON', 'NOTEBOOK_TOOLBAR_BUTTON', 'TOC_OPEN_CELL_DASHBOARD', 'TOC_HEADING_CLICKED', 'TOC_COLLAPSE_HEADERS', 'BREADCRUMB_TO_NOTEBOOK', 'BREADCRUMB_TO_CELL', 'DASHBOARD_REFRESH_BUTTON', 'DASHBOARD_FILTER_TIME', 'CELL_DASHBOARD_FILTER_SORT', 'CELL_DASHBOARD_FILTER_CODE_OUTPUT', 'CELL_DASHBOARD_FILTER_EXECUTION', 'TOC_TOOLBAR_CODE', 'TOC_TOOLBAR_MARKDOWN', 'TOC_TOOLBAR_NUMBERED', 'TOC_TOOLBAR_SHOW_HIDE', 'TOC_TOOLBAR_REFRESH', name='dashboardclickorigin'),
               nullable=False)
        
    with op.get_context().autocommit_block():
       ### adding values to a pre-existing enum
       op.execute("ALTER TYPE DashboardClickOrigin ADD VALUE 'RIGHT_DASHBOARD_SHOW_HIDE';")
       op.execute("ALTER TYPE DashboardClickOrigin ADD VALUE 'TOC_DASHBOARD_SHOW_HIDE';")
       op.execute("ALTER TYPE DashboardClickOrigin ADD VALUE 'CELL_DASHBOARD_FILTER_CODE_INPUT';")
       
       ### update any potential values that will be dropped
       op.execute("UPDATE \"DashboardEvent\" SET signal_origin = 'TOC_DASHBOARD_SHOW_HIDE' WHERE signal_origin = 'DASHBOARD_ICON_LEFT';")
       op.execute("UPDATE \"DashboardEvent\" SET signal_origin = 'RIGHT_DASHBOARD_SHOW_HIDE' WHERE signal_origin = 'DASHBOARD_ICON_RIGHT';")

       ### dropping values of an enum : required to create a new one without the old values and drop the old enum
       op.execute("ALTER TYPE DashboardClickOrigin RENAME TO OldDashboardClickOrigin")
       op.execute("CREATE TYPE DashboardClickOrigin AS ENUM('RIGHT_DASHBOARD_SHOW_HIDE', 'TOC_DASHBOARD_SHOW_HIDE', 'NOTEBOOK_CELL_BUTTON', 'NOTEBOOK_TOOLBAR_BUTTON', 'TOC_OPEN_CELL_DASHBOARD', 'TOC_HEADING_CLICKED', 'TOC_COLLAPSE_HEADERS', 'BREADCRUMB_TO_NOTEBOOK', 'BREADCRUMB_TO_CELL', 'DASHBOARD_REFRESH_BUTTON', 'DASHBOARD_FILTER_TIME', 'CELL_DASHBOARD_FILTER_SORT', 'CELL_DASHBOARD_FILTER_CODE_INPUT', 'CELL_DASHBOARD_FILTER_CODE_OUTPUT', 'CELL_DASHBOARD_FILTER_EXECUTION', 'TOC_TOOLBAR_CODE', 'TOC_TOOLBAR_MARKDOWN', 'TOC_TOOLBAR_NUMBERED', 'TOC_TOOLBAR_SHOW_HIDE', 'TOC_TOOLBAR_REFRESH')")
       op.execute((
              "ALTER TABLE \"DashboardEvent\" ALTER COLUMN signal_origin TYPE DashboardClickOrigin USING "
              "signal_origin::text::DashboardClickOrigin"
       ))
       op.execute("DROP TYPE OldDashboardClickOrigin")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DashboardEvent', schema=None) as batch_op:
        batch_op.alter_column('signal_origin',
               existing_type=postgresql.ENUM('DASHBOARD_ICON_LEFT', 'DASHBOARD_ICON_RIGHT', 'NOTEBOOK_CELL_BUTTON', 'NOTEBOOK_TOOLBAR_BUTTON', 'TOC_OPEN_CELL_DASHBOARD', 'TOC_HEADING_CLICKED', 'TOC_COLLAPSE_HEADERS', 'BREADCRUMB_TO_NOTEBOOK', 'BREADCRUMB_TO_CELL', 'DASHBOARD_REFRESH_BUTTON', 'DASHBOARD_FILTER_TIME', 'CELL_DASHBOARD_FILTER_SORT', 'CELL_DASHBOARD_FILTER_CODE_OUTPUT', 'CELL_DASHBOARD_FILTER_EXECUTION', 'TOC_TOOLBAR_CODE', 'TOC_TOOLBAR_MARKDOWN', 'TOC_TOOLBAR_NUMBERED', 'TOC_TOOLBAR_SHOW_HIDE', 'TOC_TOOLBAR_REFRESH', name='dashboardclickorigin'),
               nullable=True)
        batch_op.alter_column('click_type',
               existing_type=postgresql.ENUM('ON', 'OFF', name='clicktype'),
               nullable=True)
        batch_op.alter_column('dashboard_user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
