"""Added json_nx column to Notebook

Revision ID: b70409d3283b
Revises: cc9e0f3adfc2
Create Date: 2025-03-13 08:16:06.623206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70409d3283b'
down_revision = 'cc9e0f3adfc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notebook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json_nx', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notebook', schema=None) as batch_op:
        batch_op.drop_column('json_nx')

    # ### end Alembic commands ###
