"""Add PendingUpdateInteraction and TeammateLocation tables (PR #3)

Revision ID: c54c88b8d734
Revises: cc9e0f3adfc2
Create Date: 2026-02-13 13:33:39.587527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54c88b8d734'
down_revision = 'cc9e0f3adfc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PendingUpdateInteraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('cell_id', sa.String(length=100), nullable=True),
    sa.Column('update_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.Enum('UPDATE_NOW', 'UPDATE_LATER', 'UPDATE_ALL', 'DELETE_ALL', 'APPLY_SINGLE', 'REMOVE_SINGLE', 'OVERRIDE', name='pendingupdateaction'), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=True),
    sa.Column('sender_type', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('PendingUpdateInteraction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PendingUpdateInteraction_notebook_id'), ['notebook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_PendingUpdateInteraction_user_id'), ['user_id'], unique=False)

    op.create_table('TeammateLocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('notebook_id', sa.String(length=100), nullable=False),
    sa.Column('cell_id', sa.String(length=100), nullable=False),
    sa.Column('cell_index', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notebook_id', name='unique_user_notebook_location')
    )
    with op.batch_alter_table('TeammateLocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_TeammateLocation_notebook_id'), ['notebook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_TeammateLocation_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TeammateLocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_TeammateLocation_user_id'))
        batch_op.drop_index(batch_op.f('ix_TeammateLocation_notebook_id'))

    op.drop_table('TeammateLocation')
    with op.batch_alter_table('PendingUpdateInteraction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PendingUpdateInteraction_user_id'))
        batch_op.drop_index(batch_op.f('ix_PendingUpdateInteraction_notebook_id'))

    op.drop_table('PendingUpdateInteraction')
    # ### end Alembic commands ###
