"""Drop cells column from Notebook

Revision ID: d8095738c7b1
Revises: 19c2f19cd3ac
Create Date: 2023-12-06 12:49:23.943559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8095738c7b1'
down_revision = '19c2f19cd3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notebook', schema=None) as batch_op:
        batch_op.drop_column('cells')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notebook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cells', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
