"""Increasing columns string size

Revision ID: dc2037a9f84f
Revises: ec9fe247ecc8
Create Date: 2024-03-01 13:20:13.497415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2037a9f84f'
down_revision = 'ec9fe247ecc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CellExecution', schema=None) as batch_op:
        batch_op.alter_column('language_mimetype',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('Notebook', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=False)
        batch_op.alter_column('s3_bucket_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.alter_column('s3_object_key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notebook', schema=None) as batch_op:
        batch_op.alter_column('s3_object_key',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('s3_bucket_name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('CellExecution', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
        batch_op.alter_column('language_mimetype',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
