"""Removing NonceCache table

Revision ID: e2bb40880040
Revises: dc2037a9f84f
Create Date: 2024-03-06 14:27:40.858367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2bb40880040'
down_revision = 'dc2037a9f84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NonceCache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NonceCache',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"NonceCache_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('nonce_value', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='NonceCache_pkey'),
    sa.UniqueConstraint('nonce_value', name='NonceCache_nonce_value_key')
    )
    # ### end Alembic commands ###
