"""Change instance_id column to user_id

Revision ID: ec9fe247ecc8
Revises: 29d8b340e958
Create Date: 2024-01-31 12:59:51.158126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9fe247ecc8'
down_revision = '29d8b340e958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.alter_column('instance_id', new_column_name='user_id')

    with op.batch_alter_table('SocketConnection', schema=None) as batch_op:
        batch_op.alter_column('instance_id', new_column_name='user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SocketConnection', schema=None) as batch_op:
        batch_op.alter_column('user_id', new_column_name='instance_id')

    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.alter_column('user_id', new_column_name='instance_id')

    # ### end Alembic commands ###
